# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /src

COPY ["Domain/Domain.csproj", "Domain/"]
COPY ["Infrastructure/Infrastructure.csproj", "Infrastructure/"]
RUN dotnet restore "Infrastructure/Infrastructure.csproj"

COPY ["Domain/", "Domain/"]
COPY ["Infrastructure/", "Infrastructure/"]
RUN dotnet build "Infrastructure/Infrastructure.csproj" -c Release --no-restore
    
LABEL keep=true
