# This is a generated file. Not intended for manual editing.
services:
  jack:
    build:
      context: "G:\\repos\\agent"
      dockerfile: "Cli/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57415"
    - "--timeout=60"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "cli:dev"
    ports:
    - "127.0.0.1:57015:57000"
    - "127.0.0.1:57215:57200"
    - "127.0.0.1:57415:57415"
    volumes:
    - "G:\\repos\\agent\\Cli:/app:rw"
    - "G:\\repos\\agent:/src:rw"
    - "C:\\Users\\Detho\\AppData\\Roaming\\Microsoft\\UserSecrets:/home/app/.microsoft/usersecrets"
    - "C:\\Users\\Detho\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Detho\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.1.4\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.5\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Detho\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_7_29_17_36_42:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
